repos:
  - repo: local
    hooks:
      - id: go-generate
        name: generate
        language: system
        entry: go generate
        pass_filenames: false

      - id: go-mod-tidy
        name: tidy dependencies
        language: system
        entry: go mod tidy
        pass_filenames: false

      - id: golangci-lint-run
        name: lint
        language: system
        entry: golangci-lint run
        pass_filenames: false

      - id: go-test
        name: test
        language: system
        entry: go test -race -test.count=10 ./...
        pass_filenames: false
