// Code generated by github.com/nightmarlin/pokeapi/cmd/gettergen@v0"; DO NOT EDIT.

package pokeapi

import "context"

const EncounterMethodResource Resource = "encounter-method"

func (c *Client) GetEncounterMethod(ctx context.Context, ident string) (*EncounterMethod, error) {
	return do[*EncounterMethod](ctx, c, c.getURL(EncounterMethodResource, ident), nil)
}
func (c *Client) ListEncounterMethods(ctx context.Context, opts *ListOptions) (*Page[NamedAPIResource[EncounterMethod], EncounterMethod], error) {
	return do[*Page[NamedAPIResource[EncounterMethod], EncounterMethod]](ctx, c, c.listURL(EncounterMethodResource), opts.urlValues())
}

const EncounterConditionResource Resource = "encounter-condition"

func (c *Client) GetEncounterCondition(ctx context.Context, ident string) (*EncounterCondition, error) {
	return do[*EncounterCondition](ctx, c, c.getURL(EncounterConditionResource, ident), nil)
}
func (c *Client) ListEncounterConditions(ctx context.Context, opts *ListOptions) (*Page[NamedAPIResource[EncounterCondition], EncounterCondition], error) {
	return do[*Page[NamedAPIResource[EncounterCondition], EncounterCondition]](ctx, c, c.listURL(EncounterConditionResource), opts.urlValues())
}

const EncounterConditionValueResource Resource = "encounter-condition-value"

func (c *Client) GetEncounterConditionValue(ctx context.Context, ident string) (*EncounterConditionValue, error) {
	return do[*EncounterConditionValue](ctx, c, c.getURL(EncounterConditionValueResource, ident), nil)
}
func (c *Client) ListEncounterConditionValues(ctx context.Context, opts *ListOptions) (*Page[NamedAPIResource[EncounterConditionValue], EncounterConditionValue], error) {
	return do[*Page[NamedAPIResource[EncounterConditionValue], EncounterConditionValue]](ctx, c, c.listURL(EncounterConditionValueResource), opts.urlValues())
}
