// Code generated by github.com/nightmarlin/pokeapi/cmd/gettergen@v0"; DO NOT EDIT.

package pokeapi

import "context"

const EvolutionChainResource Resource = "evolution-chain"

// GetEvolutionChain only accepts the ID of the desired EvolutionChain.
func (c *Client) GetEvolutionChain(ctx context.Context, id string) (*EvolutionChain, error) {
	return do[*EvolutionChain](ctx, c, c.getURL(EvolutionChainResource, id), nil)
}
func (c *Client) ListEvolutionChains(ctx context.Context, opts *ListOptions) (*Page[APIResource[EvolutionChain], EvolutionChain], error) {
	return do[*Page[APIResource[EvolutionChain], EvolutionChain]](ctx, c, c.listURL(EvolutionChainResource), opts.urlValues())
}

const EvolutionTriggerResource Resource = "evolution-trigger"

func (c *Client) GetEvolutionTrigger(ctx context.Context, ident string) (*EvolutionTrigger, error) {
	return do[*EvolutionTrigger](ctx, c, c.getURL(EvolutionTriggerResource, ident), nil)
}
func (c *Client) ListEvolutionTriggers(ctx context.Context, opts *ListOptions) (*Page[NamedAPIResource[EvolutionTrigger], EvolutionTrigger], error) {
	return do[*Page[NamedAPIResource[EvolutionTrigger], EvolutionTrigger]](ctx, c, c.listURL(EvolutionTriggerResource), opts.urlValues())
}
