module github.com/nightmarlin/pokeapi

go 1.22

retract v1.0.0 // contained various spelling mistakes due to autogenerated plurals.

require (
	golang.org/x/sync v0.7.0
	golang.org/x/tools v0.21.0
)

require golang.org/x/mod v0.17.0 // indirect
