// Code generated by github.com/nightmarlin/pokeapi/cmd/gettergen@v0"; DO NOT EDIT.

package pokeapi

import "context"

const ItemResource Resource = "item"

func (c *Client) GetItem(ctx context.Context, ident string) (*Item, error) {
	return do[*Item](ctx, c, c.getURL(ItemResource, ident), nil)
}
func (c *Client) ListItems(ctx context.Context, opts *ListOptions) (*Page[NamedAPIResource[Item], Item], error) {
	return do[*Page[NamedAPIResource[Item], Item]](ctx, c, c.listURL(ItemResource), opts.urlValues())
}

const ItemAttributeResource Resource = "item-attribute"

func (c *Client) GetItemAttribute(ctx context.Context, ident string) (*ItemAttribute, error) {
	return do[*ItemAttribute](ctx, c, c.getURL(ItemAttributeResource, ident), nil)
}
func (c *Client) ListItemAttributes(ctx context.Context, opts *ListOptions) (*Page[NamedAPIResource[ItemAttribute], ItemAttribute], error) {
	return do[*Page[NamedAPIResource[ItemAttribute], ItemAttribute]](ctx, c, c.listURL(ItemAttributeResource), opts.urlValues())
}

const ItemCategoryResource Resource = "item-category"

func (c *Client) GetItemCategory(ctx context.Context, ident string) (*ItemCategory, error) {
	return do[*ItemCategory](ctx, c, c.getURL(ItemCategoryResource, ident), nil)
}
func (c *Client) ListItemCategories(ctx context.Context, opts *ListOptions) (*Page[NamedAPIResource[ItemCategory], ItemCategory], error) {
	return do[*Page[NamedAPIResource[ItemCategory], ItemCategory]](ctx, c, c.listURL(ItemCategoryResource), opts.urlValues())
}

const ItemFlingEffectResource Resource = "item-fling-effect"

func (c *Client) GetItemFlingEffect(ctx context.Context, ident string) (*ItemFlingEffect, error) {
	return do[*ItemFlingEffect](ctx, c, c.getURL(ItemFlingEffectResource, ident), nil)
}
func (c *Client) ListItemFlingEffects(ctx context.Context, opts *ListOptions) (*Page[NamedAPIResource[ItemFlingEffect], ItemFlingEffect], error) {
	return do[*Page[NamedAPIResource[ItemFlingEffect], ItemFlingEffect]](ctx, c, c.listURL(ItemFlingEffectResource), opts.urlValues())
}

const ItemPocketResource Resource = "item-pocket"

func (c *Client) GetItemPocket(ctx context.Context, ident string) (*ItemPocket, error) {
	return do[*ItemPocket](ctx, c, c.getURL(ItemPocketResource, ident), nil)
}
func (c *Client) ListItemPockets(ctx context.Context, opts *ListOptions) (*Page[NamedAPIResource[ItemPocket], ItemPocket], error) {
	return do[*Page[NamedAPIResource[ItemPocket], ItemPocket]](ctx, c, c.listURL(ItemPocketResource), opts.urlValues())
}
