// Code generated by github.com/nightmarlin/pokeapi/cmd/gettergen@v0"; DO NOT EDIT.

package pokeapi

import "context"

const LanguageResource Resource = "language"

func (c *Client) GetLanguage(ctx context.Context, ident string) (*Language, error) {
	return do[*Language](ctx, c, c.getURL(LanguageResource, ident), nil)
}
func (c *Client) ListLanguages(ctx context.Context, opts *ListOptions) (*Page[NamedAPIResource[Language], Language], error) {
	return do[*Page[NamedAPIResource[Language], Language]](ctx, c, c.listURL(LanguageResource), opts.urlValues())
}
